// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/java_features.proto

// Protobuf Java Version: 3.25.5
package com.google.protobuf;

public final class JavaFeaturesProto {
  private JavaFeaturesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.protobuf.JavaFeaturesProto.java);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JavaFeaturesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.JavaFeatures)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Whether or not to treat an enum field as closed.  This option is only
     * applicable to enum fields, and will be removed in the future.  It is
     * consistent with the legacy behavior of using proto3 enum types for proto2
     * fields.
     * </pre>
     *
     * <code>optional bool legacy_closed_enum = 1 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the legacyClosedEnum field is set.
     */
    boolean hasLegacyClosedEnum();
    /**
     * <pre>
     * Whether or not to treat an enum field as closed.  This option is only
     * applicable to enum fields, and will be removed in the future.  It is
     * consistent with the legacy behavior of using proto3 enum types for proto2
     * fields.
     * </pre>
     *
     * <code>optional bool legacy_closed_enum = 1 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The legacyClosedEnum.
     */
    boolean getLegacyClosedEnum();

    /**
     * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the utf8Validation field is set.
     */
    boolean hasUtf8Validation();
    /**
     * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The utf8Validation.
     */
    com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation getUtf8Validation();

    /**
     * <pre>
     * Whether to use the old default outer class name scheme, or the new feature
     * which adds a "Proto" suffix to the outer class name.
     *
     * Users will not be able to set this option, because we removed it in the
     * same edition that it was introduced. But we use it to determine which
     * naming scheme to use for outer class name defaults.
     * </pre>
     *
     * <code>optional bool use_old_outer_classname_default = 4 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the useOldOuterClassnameDefault field is set.
     */
    boolean hasUseOldOuterClassnameDefault();
    /**
     * <pre>
     * Whether to use the old default outer class name scheme, or the new feature
     * which adds a "Proto" suffix to the outer class name.
     *
     * Users will not be able to set this option, because we removed it in the
     * same edition that it was introduced. But we use it to determine which
     * naming scheme to use for outer class name defaults.
     * </pre>
     *
     * <code>optional bool use_old_outer_classname_default = 4 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The useOldOuterClassnameDefault.
     */
    boolean getUseOldOuterClassnameDefault();
  }
  /**
   * Protobuf type {@code pb.JavaFeatures}
   */
  public static final class JavaFeatures extends
      com.google.protobuf.FlattenedGeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.JavaFeatures)
      JavaFeaturesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JavaFeatures.newBuilder() to construct.
    private JavaFeatures(com.google.protobuf.FlattenedGeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JavaFeatures() {
      utf8Validation_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JavaFeatures();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.FlattenedGeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.JavaFeaturesProto.JavaFeatures.class, com.google.protobuf.JavaFeaturesProto.JavaFeatures.Builder.class);
    }

    /**
     * <pre>
     * The UTF8 validation strategy to use.  See go/editions-utf8-validation for
     * more information on this feature.
     * </pre>
     *
     * Protobuf enum {@code pb.JavaFeatures.Utf8Validation}
     */
    public enum Utf8Validation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Invalid default, which should never be used.
       * </pre>
       *
       * <code>UTF8_VALIDATION_UNKNOWN = 0;</code>
       */
      UTF8_VALIDATION_UNKNOWN(0),
      /**
       * <pre>
       * Respect the UTF8 validation behavior specified by the global
       * utf8_validation feature.
       * </pre>
       *
       * <code>DEFAULT = 1;</code>
       */
      DEFAULT(1),
      /**
       * <pre>
       * Verifies UTF8 validity overriding the global utf8_validation
       * feature. This represents the legacy java_string_check_utf8 option.
       * </pre>
       *
       * <code>VERIFY = 2;</code>
       */
      VERIFY(2),
      ;

      /**
       * <pre>
       * Invalid default, which should never be used.
       * </pre>
       *
       * <code>UTF8_VALIDATION_UNKNOWN = 0;</code>
       */
      public static final int UTF8_VALIDATION_UNKNOWN_VALUE = 0;
      /**
       * <pre>
       * Respect the UTF8 validation behavior specified by the global
       * utf8_validation feature.
       * </pre>
       *
       * <code>DEFAULT = 1;</code>
       */
      public static final int DEFAULT_VALUE = 1;
      /**
       * <pre>
       * Verifies UTF8 validity overriding the global utf8_validation
       * feature. This represents the legacy java_string_check_utf8 option.
       * </pre>
       *
       * <code>VERIFY = 2;</code>
       */
      public static final int VERIFY_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Utf8Validation valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Utf8Validation forNumber(int value) {
        switch (value) {
          case 0: return UTF8_VALIDATION_UNKNOWN;
          case 1: return DEFAULT;
          case 2: return VERIFY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Utf8Validation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Utf8Validation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Utf8Validation>() {
              public Utf8Validation findValueByNumber(int number) {
                return Utf8Validation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.protobuf.JavaFeaturesProto.JavaFeatures.getDescriptor().getEnumTypes().get(0);
      }

      private static final Utf8Validation[] VALUES = values();

      public static Utf8Validation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Utf8Validation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.JavaFeatures.Utf8Validation)
    }

    private int bitField0_;
    public static final int LEGACY_CLOSED_ENUM_FIELD_NUMBER = 1;
    private boolean legacyClosedEnum_ = false;
    /**
     * <pre>
     * Whether or not to treat an enum field as closed.  This option is only
     * applicable to enum fields, and will be removed in the future.  It is
     * consistent with the legacy behavior of using proto3 enum types for proto2
     * fields.
     * </pre>
     *
     * <code>optional bool legacy_closed_enum = 1 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the legacyClosedEnum field is set.
     */
    @java.lang.Override
    public boolean hasLegacyClosedEnum() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Whether or not to treat an enum field as closed.  This option is only
     * applicable to enum fields, and will be removed in the future.  It is
     * consistent with the legacy behavior of using proto3 enum types for proto2
     * fields.
     * </pre>
     *
     * <code>optional bool legacy_closed_enum = 1 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The legacyClosedEnum.
     */
    @java.lang.Override
    public boolean getLegacyClosedEnum() {
      return legacyClosedEnum_;
    }

    public static final int UTF8_VALIDATION_FIELD_NUMBER = 2;
    private int utf8Validation_ = 0;
    /**
     * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the utf8Validation field is set.
     */
    @java.lang.Override public boolean hasUtf8Validation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The utf8Validation.
     */
    @java.lang.Override public com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation getUtf8Validation() {
      com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation result = com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.forNumber(utf8Validation_);
      return result == null ? com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.UTF8_VALIDATION_UNKNOWN : result;
    }

    public static final int USE_OLD_OUTER_CLASSNAME_DEFAULT_FIELD_NUMBER = 4;
    private boolean useOldOuterClassnameDefault_ = false;
    /**
     * <pre>
     * Whether to use the old default outer class name scheme, or the new feature
     * which adds a "Proto" suffix to the outer class name.
     *
     * Users will not be able to set this option, because we removed it in the
     * same edition that it was introduced. But we use it to determine which
     * naming scheme to use for outer class name defaults.
     * </pre>
     *
     * <code>optional bool use_old_outer_classname_default = 4 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the useOldOuterClassnameDefault field is set.
     */
    @java.lang.Override
    public boolean hasUseOldOuterClassnameDefault() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Whether to use the old default outer class name scheme, or the new feature
     * which adds a "Proto" suffix to the outer class name.
     *
     * Users will not be able to set this option, because we removed it in the
     * same edition that it was introduced. But we use it to determine which
     * naming scheme to use for outer class name defaults.
     * </pre>
     *
     * <code>optional bool use_old_outer_classname_default = 4 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The useOldOuterClassnameDefault.
     */
    @java.lang.Override
    public boolean getUseOldOuterClassnameDefault() {
      return useOldOuterClassnameDefault_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, legacyClosedEnum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, utf8Validation_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(4, useOldOuterClassnameDefault_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, legacyClosedEnum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, utf8Validation_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, useOldOuterClassnameDefault_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.JavaFeaturesProto.JavaFeatures)) {
        return super.equals(obj);
      }
      com.google.protobuf.JavaFeaturesProto.JavaFeatures other = (com.google.protobuf.JavaFeaturesProto.JavaFeatures) obj;

      if (hasLegacyClosedEnum() != other.hasLegacyClosedEnum()) return false;
      if (hasLegacyClosedEnum()) {
        if (getLegacyClosedEnum()
            != other.getLegacyClosedEnum()) return false;
      }
      if (hasUtf8Validation() != other.hasUtf8Validation()) return false;
      if (hasUtf8Validation()) {
        if (utf8Validation_ != other.utf8Validation_) return false;
      }
      if (hasUseOldOuterClassnameDefault() != other.hasUseOldOuterClassnameDefault()) return false;
      if (hasUseOldOuterClassnameDefault()) {
        if (getUseOldOuterClassnameDefault()
            != other.getUseOldOuterClassnameDefault()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLegacyClosedEnum()) {
        hash = (37 * hash) + LEGACY_CLOSED_ENUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getLegacyClosedEnum());
      }
      if (hasUtf8Validation()) {
        hash = (37 * hash) + UTF8_VALIDATION_FIELD_NUMBER;
        hash = (53 * hash) + utf8Validation_;
      }
      if (hasUseOldOuterClassnameDefault()) {
        hash = (37 * hash) + USE_OLD_OUTER_CLASSNAME_DEFAULT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUseOldOuterClassnameDefault());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.FlattenedGeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.FlattenedGeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.FlattenedGeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.FlattenedGeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.FlattenedGeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.FlattenedGeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.JavaFeaturesProto.JavaFeatures prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.FlattenedGeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.JavaFeatures}
     */
    public static final class Builder extends
        com.google.protobuf.FlattenedGeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.JavaFeatures)
        com.google.protobuf.JavaFeaturesProto.JavaFeaturesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.FlattenedGeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.JavaFeaturesProto.JavaFeatures.class, com.google.protobuf.JavaFeaturesProto.JavaFeatures.Builder.class);
      }

      // Construct using com.google.protobuf.JavaFeaturesProto.JavaFeatures.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.FlattenedGeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        legacyClosedEnum_ = false;
        utf8Validation_ = 0;
        useOldOuterClassnameDefault_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_descriptor;
      }

      @java.lang.Override
      public com.google.protobuf.JavaFeaturesProto.JavaFeatures getDefaultInstanceForType() {
        return com.google.protobuf.JavaFeaturesProto.JavaFeatures.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.protobuf.JavaFeaturesProto.JavaFeatures build() {
        com.google.protobuf.JavaFeaturesProto.JavaFeatures result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.protobuf.JavaFeaturesProto.JavaFeatures buildPartial() {
        com.google.protobuf.JavaFeaturesProto.JavaFeatures result = new com.google.protobuf.JavaFeaturesProto.JavaFeatures(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.protobuf.JavaFeaturesProto.JavaFeatures result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.legacyClosedEnum_ = legacyClosedEnum_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.utf8Validation_ = utf8Validation_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.useOldOuterClassnameDefault_ = useOldOuterClassnameDefault_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.JavaFeaturesProto.JavaFeatures) {
          return mergeFrom((com.google.protobuf.JavaFeaturesProto.JavaFeatures)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.JavaFeaturesProto.JavaFeatures other) {
        if (other == com.google.protobuf.JavaFeaturesProto.JavaFeatures.getDefaultInstance()) return this;
        if (other.hasLegacyClosedEnum()) {
          setLegacyClosedEnum(other.getLegacyClosedEnum());
        }
        if (other.hasUtf8Validation()) {
          setUtf8Validation(other.getUtf8Validation());
        }
        if (other.hasUseOldOuterClassnameDefault()) {
          setUseOldOuterClassnameDefault(other.getUseOldOuterClassnameDefault());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                legacyClosedEnum_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                int tmpRaw = input.readEnum();
                com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation tmpValue =
                    com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(2, tmpRaw);
                } else {
                  utf8Validation_ = tmpRaw;
                  bitField0_ |= 0x00000002;
                }
                break;
              } // case 16
              case 32: {
                useOldOuterClassnameDefault_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean legacyClosedEnum_ ;
      /**
       * <pre>
       * Whether or not to treat an enum field as closed.  This option is only
       * applicable to enum fields, and will be removed in the future.  It is
       * consistent with the legacy behavior of using proto3 enum types for proto2
       * fields.
       * </pre>
       *
       * <code>optional bool legacy_closed_enum = 1 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return Whether the legacyClosedEnum field is set.
       */
      @java.lang.Override
      public boolean hasLegacyClosedEnum() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Whether or not to treat an enum field as closed.  This option is only
       * applicable to enum fields, and will be removed in the future.  It is
       * consistent with the legacy behavior of using proto3 enum types for proto2
       * fields.
       * </pre>
       *
       * <code>optional bool legacy_closed_enum = 1 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return The legacyClosedEnum.
       */
      @java.lang.Override
      public boolean getLegacyClosedEnum() {
        return legacyClosedEnum_;
      }
      /**
       * <pre>
       * Whether or not to treat an enum field as closed.  This option is only
       * applicable to enum fields, and will be removed in the future.  It is
       * consistent with the legacy behavior of using proto3 enum types for proto2
       * fields.
       * </pre>
       *
       * <code>optional bool legacy_closed_enum = 1 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @param value The legacyClosedEnum to set.
       * @return This builder for chaining.
       */
      public Builder setLegacyClosedEnum(boolean value) {

        legacyClosedEnum_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether or not to treat an enum field as closed.  This option is only
       * applicable to enum fields, and will be removed in the future.  It is
       * consistent with the legacy behavior of using proto3 enum types for proto2
       * fields.
       * </pre>
       *
       * <code>optional bool legacy_closed_enum = 1 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearLegacyClosedEnum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        legacyClosedEnum_ = false;
        onChanged();
        return this;
      }

      private int utf8Validation_ = 0;
      /**
       * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return Whether the utf8Validation field is set.
       */
      @java.lang.Override public boolean hasUtf8Validation() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return The utf8Validation.
       */
      @java.lang.Override
      public com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation getUtf8Validation() {
        com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation result = com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.forNumber(utf8Validation_);
        return result == null ? com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.UTF8_VALIDATION_UNKNOWN : result;
      }
      /**
       * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @param value The utf8Validation to set.
       * @return This builder for chaining.
       */
      public Builder setUtf8Validation(com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        utf8Validation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearUtf8Validation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        utf8Validation_ = 0;
        onChanged();
        return this;
      }

      private boolean useOldOuterClassnameDefault_ ;
      /**
       * <pre>
       * Whether to use the old default outer class name scheme, or the new feature
       * which adds a "Proto" suffix to the outer class name.
       *
       * Users will not be able to set this option, because we removed it in the
       * same edition that it was introduced. But we use it to determine which
       * naming scheme to use for outer class name defaults.
       * </pre>
       *
       * <code>optional bool use_old_outer_classname_default = 4 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return Whether the useOldOuterClassnameDefault field is set.
       */
      @java.lang.Override
      public boolean hasUseOldOuterClassnameDefault() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Whether to use the old default outer class name scheme, or the new feature
       * which adds a "Proto" suffix to the outer class name.
       *
       * Users will not be able to set this option, because we removed it in the
       * same edition that it was introduced. But we use it to determine which
       * naming scheme to use for outer class name defaults.
       * </pre>
       *
       * <code>optional bool use_old_outer_classname_default = 4 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return The useOldOuterClassnameDefault.
       */
      @java.lang.Override
      public boolean getUseOldOuterClassnameDefault() {
        return useOldOuterClassnameDefault_;
      }
      /**
       * <pre>
       * Whether to use the old default outer class name scheme, or the new feature
       * which adds a "Proto" suffix to the outer class name.
       *
       * Users will not be able to set this option, because we removed it in the
       * same edition that it was introduced. But we use it to determine which
       * naming scheme to use for outer class name defaults.
       * </pre>
       *
       * <code>optional bool use_old_outer_classname_default = 4 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @param value The useOldOuterClassnameDefault to set.
       * @return This builder for chaining.
       */
      public Builder setUseOldOuterClassnameDefault(boolean value) {

        useOldOuterClassnameDefault_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether to use the old default outer class name scheme, or the new feature
       * which adds a "Proto" suffix to the outer class name.
       *
       * Users will not be able to set this option, because we removed it in the
       * same edition that it was introduced. But we use it to determine which
       * naming scheme to use for outer class name defaults.
       * </pre>
       *
       * <code>optional bool use_old_outer_classname_default = 4 [retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearUseOldOuterClassnameDefault() {
        bitField0_ = (bitField0_ & ~0x00000004);
        useOldOuterClassnameDefault_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.JavaFeatures)
    }

    // @@protoc_insertion_point(class_scope:pb.JavaFeatures)
    private static final com.google.protobuf.JavaFeaturesProto.JavaFeatures DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.JavaFeaturesProto.JavaFeatures();
    }

    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<JavaFeatures>
        PARSER = new com.google.protobuf.AbstractParser<JavaFeatures>() {
      @java.lang.Override
      public JavaFeatures parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<JavaFeatures> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JavaFeatures> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.JavaFeaturesProto.JavaFeatures getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int JAVA_FIELD_NUMBER = 1001;
  /**
   * <code>extend .google.protobuf.FeatureSet { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FeatureSet,
      com.google.protobuf.JavaFeaturesProto.JavaFeatures> java = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.protobuf.JavaFeaturesProto.JavaFeatures.class,
        com.google.protobuf.JavaFeaturesProto.JavaFeatures.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_JavaFeatures_descriptor;
  private static final 
    com.google.protobuf.FlattenedGeneratedMessageV3.FieldAccessorTable
      internal_static_pb_JavaFeatures_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#google/protobuf/java_features.proto\022\002p" +
      "b\032 google/protobuf/descriptor.proto\"\314\005\n\014" +
      "JavaFeatures\022\376\001\n\022legacy_closed_enum\030\001 \001(" +
      "\010B\341\001\210\001\001\230\001\004\230\001\001\242\001\t\022\004true\030\204\007\242\001\n\022\005false\030\347\007\262\001" +
      "\273\001\010\350\007\020\350\007\032\262\001The legacy closed enum behavi" +
      "or in Java is deprecated and is schedule" +
      "d to be removed in edition 2025.  See ht" +
      "tp://protobuf.dev/programming-guides/enu" +
      "m/#java for more information.\022\237\002\n\017utf8_v" +
      "alidation\030\002 \001(\0162\037.pb.JavaFeatures.Utf8Va" +
      "lidationB\344\001\210\001\001\230\001\004\230\001\001\242\001\014\022\007DEFAULT\030\204\007\262\001\310\001\010" +
      "\350\007\020\351\007\032\277\001The Java-specific utf8 validatio" +
      "n feature is deprecated and is scheduled" +
      " to be removed in edition 2025.  Utf8 va" +
      "lidation behavior should use the global " +
      "cross-language utf8_validation feature.\022" +
      "Q\n\037use_old_outer_classname_default\030\004 \001(\010" +
      "B(\210\001\001\230\001\001\242\001\t\022\004true\030\204\007\242\001\n\022\005false\030\351\007\262\001\006\010\351\007 " +
      "\351\007\"F\n\016Utf8Validation\022\033\n\027UTF8_VALIDATION_" +
      "UNKNOWN\020\000\022\013\n\007DEFAULT\020\001\022\n\n\006VERIFY\020\002:<\n\004ja" +
      "va\022\033.google.protobuf.FeatureSet\030\351\007 \001(\0132\020" +
      ".pb.JavaFeaturesB(\n\023com.google.protobufB" +
      "\021JavaFeaturesProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_pb_JavaFeatures_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_JavaFeatures_fieldAccessorTable = new
      com.google.protobuf.FlattenedGeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_JavaFeatures_descriptor,
        new java.lang.String[] { "LegacyClosedEnum", "Utf8Validation", "UseOldOuterClassnameDefault", });
    java.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
